### L02 NumPy Module

by Yan Zhan (2020)

### What it NumPy

NumPy is the fundamental package for scientific computing with Python. It is well documented online: www.numpy.org
np is usually used as the short name for numpy

In [3]:
# To use NumPy, you need to import it as a module
import numpy as np

# numpy array
a = np.array([1, 2, 3, 4])

print(type(a))

<class 'numpy.ndarray'>


In [4]:
# 1st element
print(a[0])

1


In [8]:
# last element
print(a[3])
# or
print(a[-1])

4
4


In [7]:
# 1st to 3nd element 
# Note: the element with index "3" is not include
print(a[0:3])

[1 2 3]


### Some useful preset arrays

In [13]:
# zeros
a = np.zeros(3)
print("a = {}".format(a))

# 3 by 4 matrix
b = np.zeros([3, 4])
print("b = {}".format(b))

# get the size of the array
print("size of a is {}, size of b is {}".format(a.shape, b.shape))

a = [0. 0. 0.]
b = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
size of a is (3,), size of b is (3, 4)


In [15]:
# ones
c = np.ones([2, 3])
print("c = {}".format(c))

c = [[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# empty array with NaN (Not a Number)
d = np.ones([2, 3]) * np.nan
print("d = {}".format(d))

d = [[nan nan nan]
 [nan nan nan]]


In [20]:
# random arrays
# Create an array of the given shape and 
# populate it with random samples from a 
# uniform distribution over [0, 1).
e = np.random.rand(5, 6) # different from np.zeros([5, 6])
print(e)

[[0.99019465 0.04333574 0.76049372 0.91546157 0.97428392 0.77508359]
 [0.8188577  0.2780579  0.98921261 0.17655138 0.05071514 0.60210888]
 [0.3258789  0.66433249 0.66820866 0.43939108 0.54439902 0.78130728]
 [0.13644429 0.26823797 0.70266653 0.75172151 0.43554786 0.24068949]
 [0.35023288 0.07436832 0.89852013 0.97045714 0.5352135  0.54845642]]


In [22]:
# Return an array with the “standard normal” distribution.
f = np.random.randn(5, 6) # different from np.zeros([5, 6])
print(f)

[[-1.92494068 -1.26664931  0.27007927  0.21451145  1.77892667 -0.26229448]
 [ 0.45978313  0.44470892  0.43482363 -0.7472408   1.67832974 -0.2695291 ]
 [ 0.76865628  0.08748573  1.69626611  0.04550032 -1.02098194 -1.62661445]
 [-0.79193804 -1.79429904  1.35826153 -0.52677418  0.57920091 -0.09619149]
 [-1.60125763 -1.21241075 -0.36049126  1.79301961  1.93677673  0.66612726]]


### numpy.linspace

Return evenly spaced numbers over a specified interval.

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [25]:
# create an array
g = np.linspace(0, 1, 101)
print(g)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


### numpy.arange

Return evenly spaced values within a given interval.

numpy.arange([start, ]stop, [step, ]dtype=None)

In [27]:
# create an array
h = np.arange(0, 101)
print(h)
# note the number "101" is not included.

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


### Basic operation

In [63]:
a = np.array([[1,2,3],
              [4,5,6]])

print("a is")
print(a)

print("a + a is")
print(a + a)

print("a - a is")
print(a - a)

print("a * a is")
print(a * a) # note this is multiplication of each element

print("a x a is")
print(np.dot(a, a.T)) # note this is multiplication of matrices
# .T is transpose to make sure the the column # of the 1st matrix
# = the row # of the 2nd matrix
# (https://en.wikipedia.org/wiki/Matrix_multiplication)

print("a / a is")
print(a/a) # note this is dividing of each element

# calculate the inverse of a matrix
b = np.array([[1,2],
              [3,4]])
print("the inverse matrix of b is ")
c = np.linalg.inv(b)
print(c) # note this is dividing of each element
# test
print("test b x c")
print(np.dot(b,c))
print("test c x b")
print(np.dot(c,b))

a is
[[1 2 3]
 [4 5 6]]
a + a is
[[ 2  4  6]
 [ 8 10 12]]
a - a is
[[0 0 0]
 [0 0 0]]
a * a is
[[ 1  4  9]
 [16 25 36]]
a x a is
[[14 32]
 [32 77]]
a / a is
[[1. 1. 1.]
 [1. 1. 1.]]
the inverse matrix of b is 
[[-2.   1. ]
 [ 1.5 -0.5]]
test b x c
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
test c x b
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


### Some useful operations

In [28]:
# cumulative sum
a = np.arange(0, 101)
sum_a = a.cumsum()
print(sum_a)

[   0    1    3    6   10   15   21   28   36   45   55   66   78   91
  105  120  136  153  171  190  210  231  253  276  300  325  351  378
  406  435  465  496  528  561  595  630  666  703  741  780  820  861
  903  946  990 1035 1081 1128 1176 1225 1275 1326 1378 1431 1485 1540
 1596 1653 1711 1770 1830 1891 1953 2016 2080 2145 2211 2278 2346 2415
 2485 2556 2628 2701 2775 2850 2926 3003 3081 3160 3240 3321 3403 3486
 3570 3655 3741 3828 3916 4005 4095 4186 4278 4371 4465 4560 4656 4753
 4851 4950 5050]


In [41]:
# reshape
b = np.zeros([3, 4])
print(b.shape)

# flatten the array
c = b.reshape([-1])
print(c.shape)

# reshape back
d = c.reshape(b.shape)
print(d.shape)

(3, 4)
(12,)
(3, 4)


In [69]:
# flip the matrix
a = np.array([[1,2,3],
              [4,5,6]])

# Flip array in the up/down direction.
b = np.flipud(a)

# Flip array in the left/right direction.
c = np.fliplr(a)

print("a = {}".format(a))
print("b = {}".format(b))
print("b = {}".format(c))

a = [[1 2 3]
 [4 5 6]]
b = [[4 5 6]
 [1 2 3]]
b = [[3 2 1]
 [6 5 4]]
